#!/bin/bash

SELF=$(realpath $0)
DIR=$(dirname $SELF)
TARGET=$(cat $DIR/yeico.target)

case "$1" in
    clean)
    cd $(dirname $SELF)
    rm -fr ~/.nerves/artifacts/yeico_firmware_$TARGET-*
    rm -fr deps _build .nerves
    ;;
    artifact)
    cd $(dirname $SELF)
    mix deps.get
    $SELF make
    mix nerves.artifact
    ls -l yeico_firmware_$TARGET-*.tar.gz
    mv yeico_firmware_$TARGET-*.tar.gz ~/.nerves/dl
    ls -l ~/.nerves/dl/yeico_firmware_$TARGET-*.tar.gz
    ;;
    setup)
    cd $(dirname $SELF)
    deps/nerves_system_br/create-build.sh nerves_defconfig .nerves/artifacts/yeico_firmware_$TARGET-portable-1.32.0
    cd .nerves/artifacts/yeico_firmware_$TARGET-portable-1.32.0
    echo Running within an screen session
    $SELF patch | tee ${SELF%.*}.log
    [ $# -gt 0 ] && shift
    [ $# -gt 0 ] && echo Executing: "$@"
    [ $# -gt 0 ] && bash -c "$@"
    [ $# -gt 0 ] || bash
    ;;
    patch)
    counter=0
    for p in $(dirname $SELF)/patches/*.patch; do
        echo $p
        array=(${p//-/ })
        package=${array[1]}
        version=${array[2]}
        dir=build/$package-$version
        [ -d $dir ] || make $package-patch
        [ -d $dir ] || echo $dir not found
        [ -d $dir ] || continue
        [ -f $dir/.yeico_patched ] || echo Patching: $dir
        [ -f $dir/.yeico_patched ] || (cd build/$package-$version && (patch -p1 < $p))
        [ -f $dir/.yeico_patched ] || counter=$((counter + 1))
        [ -f $dir/.yeico_patched ] || touch $dir/.yeico_patched
    done
    echo Total patched: $counter
    ;;
    *)
    cd $(dirname $SELF)
    mix deps.get
    screen $SELF setup "$@"
    ;;
esac
