#!/bin/bash

SELF_RP=$(realpath $0)
SELF_DIR=$(dirname $SELF_RP)
SELF_LOG=${SELF_RP%.*}.log
TARGET=$(cat $SELF_DIR/yeico.target)

# uncomment for debugging
# exec > >(tee -a $SELF_LOG) 2>&1

case "$1" in
    clean)
    cd $SELF_DIR
    rm -fr ~/.nerves/artifacts/yeico_firmware_$TARGET-*
    rm -fr deps _build .nerves
    ;;
    cross)
    cd $SELF_DIR
    cd .nerves/artifacts/yeico_firmware_$TARGET-portable-1.32.0
    rm -f images/*_sdk-buildroot.tar.gz
    $SELF_RP BR2_SDK_PREFIX=cross-$TARGET make sdk
    ls -l images/cross-$TARGET.tar.gz || (echo Cross build failed; exit 1)
    mv images/cross-$TARGET.tar.gz ~/.nerves/dl/cross-$TARGET.tar.gz
    cd $SELF_DIR
    cross_build=~/.nerves/dl/cross-$TARGET.txt
    echo STAMP=$(date +"%Y-%m-%dT%H:%M:%S.%3N") > $cross_build
    echo REPO=$(git remote get-url origin) >> $cross_build
    echo COMMIT=$(git rev-parse HEAD) >> $cross_build
    echo BRANCH=$(git rev-parse --abbrev-ref HEAD) >> $cross_build
    echo DIRTY=$([ -n "$(git status --porcelain)" ] && echo yes || echo no) >> $cross_build
    ls -l ~/.nerves/dl/cross-$TARGET.*
    ;;
    artifact)
    cd $SELF_DIR
    mix deps.get
    mix nerves.artifact
    ls -l yeico_firmware_$TARGET-*.tar.gz
    mv yeico_firmware_$TARGET-*.tar.gz ~/.nerves/dl
    ls -l ~/.nerves/dl/yeico_firmware_$TARGET-*.tar.gz
    ;;
    shell)
    cd $SELF_DIR
    deps/nerves_system_br/create-build.sh nerves_defconfig .nerves/artifacts/yeico_firmware_$TARGET-portable-1.32.0
    cd .nerves/artifacts/yeico_firmware_$TARGET-portable-1.32.0
    echo Running within an screen session
    $SELF_RP patch | tee $SELF_LOG
    [ $# -gt 0 ] && shift
    [ $# -gt 0 ] && echo Executing: $@
    [ $# -gt 0 ] && (echo $@ | bash)
    [ $# -gt 0 ] || bash
    ;;
    patch)
    counter=0
    for p in $SELF_DIR/patches/*.patch; do
        echo $p
        array=(${p//-/ })
        package=${array[1]}
        version=${array[2]}
        dir=build/$package-$version
        [ -d $dir ] || make $package-patch
        [ -d $dir ] || echo $dir not found
        [ -d $dir ] || continue
        [ -f $dir/.yeico_patched ] || echo Patching: $dir
        [ -f $dir/.yeico_patched ] || (cd build/$package-$version && (patch -p1 < $p))
        [ -f $dir/.yeico_patched ] || counter=$((counter + 1))
        [ -f $dir/.yeico_patched ] || touch $dir/.yeico_patched
    done
    echo Total patched: $counter
    ;;
    *)
    cd $SELF_DIR
    mix deps.get
    screen $SELF_RP shell $@
    ;;
esac
